# Generated by Django 3.1.7 on 2021-03-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210318_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
