# Generated by Django 3.1.7 on 2021-03-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210327_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
