# Generated by Django 3.1.7 on 2021-03-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicetypes',
        ),
    ]
