# Generated by Django 3.1.7 on 2021-03-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_services_servicetypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='type',
            new_name='service_type',
        ),
    ]
