# Generated by Django 3.1.7 on 2021-04-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
