# Generated by Django 3.1.7 on 2021-04-03 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210403_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
