# Generated by Django 3.1.7 on 2021-04-04 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210404_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
