# Generated by Django 3.1.7 on 2021-05-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
