# Generated by Django 3.1.7 on 2021-05-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
