# Generated by Django 3.1.7 on 2021-05-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210508_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='queue',
            field=models.IntegerField(unique=True),
        ),
    ]
