# Generated by Django 3.1.7 on 2021-05-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210508_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
