# Generated by Django 3.1.7 on 2021-05-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='doctor',
        ),
    ]
