# Generated by Django 3.1.7 on 2021-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_event_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='queue',
            field=models.IntegerField(),
        ),
    ]
